#

#Create destination
{"city": "Medellin",
"distance": 420.5,
"price": 150000
}

#Create vehicle
{"plate": "ABZ-532",
"model" : "Mercedez",
"capacity" : 15,
"driver" : "John",
"destination_id":1
}

#Others
.venv\Scripts\activate
uvicorn main:app --reload
